#ifndef INPUT_HPP
#define INPUT_HPP

#include <padscore/kpad.h>
#include <vpad/input.h>


// Wii U GamePad buttons.
const int VPAD_BUTTONS[] = {
    VPAD_BUTTON_A,
    VPAD_BUTTON_B,
    VPAD_BUTTON_X,
    VPAD_BUTTON_Y,
    VPAD_BUTTON_LEFT,
    VPAD_BUTTON_RIGHT,
    VPAD_BUTTON_UP,
    VPAD_BUTTON_DOWN,
    VPAD_BUTTON_L,
    VPAD_BUTTON_R,
    VPAD_BUTTON_ZL,
    VPAD_BUTTON_ZR,
    VPAD_BUTTON_PLUS,
    VPAD_BUTTON_MINUS,
    VPAD_BUTTON_STICK_L,
    VPAD_BUTTON_STICK_R,
    VPAD_BUTTON_HOME,
    VPAD_BUTTON_TV,
    VPAD_BUTTON_SYNC
};

// Wii Remote buttons.
const int WPAD_BUTTONS[] = {
    WPAD_BUTTON_A,
    WPAD_BUTTON_B,
    WPAD_BUTTON_1,
    WPAD_BUTTON_2,
    WPAD_BUTTON_LEFT,
    WPAD_BUTTON_RIGHT,
    WPAD_BUTTON_UP,
    WPAD_BUTTON_DOWN,
    0,
    0,
    0,
    0,
    WPAD_BUTTON_PLUS,
    WPAD_BUTTON_MINUS,
    0,
    0,
    WPAD_BUTTON_HOME,
    0,
    0
};

// Wii Classic Controller buttons.
const int WPAD_CLASSIC_BUTTONS[] = {
    WPAD_CLASSIC_BUTTON_A,
    WPAD_CLASSIC_BUTTON_B,
    WPAD_CLASSIC_BUTTON_X,
    WPAD_CLASSIC_BUTTON_Y,
    WPAD_CLASSIC_BUTTON_LEFT,
    WPAD_CLASSIC_BUTTON_RIGHT,
    WPAD_CLASSIC_BUTTON_UP,
    WPAD_CLASSIC_BUTTON_DOWN,
    WPAD_CLASSIC_BUTTON_L,
    WPAD_CLASSIC_BUTTON_R,
    WPAD_CLASSIC_BUTTON_ZL,
    WPAD_CLASSIC_BUTTON_ZR,
    WPAD_CLASSIC_BUTTON_PLUS,
    WPAD_CLASSIC_BUTTON_MINUS,
    0,
    0,
    WPAD_CLASSIC_BUTTON_HOME,
    0,
    0
};

// Wii U Pro Controller buttons.
const int WPAD_PRO_BUTTONS[] = {
    WPAD_PRO_BUTTON_A,
    WPAD_PRO_BUTTON_B,
    WPAD_PRO_BUTTON_X,
    WPAD_PRO_BUTTON_Y,
    WPAD_PRO_BUTTON_LEFT,
    WPAD_PRO_BUTTON_RIGHT,
    WPAD_PRO_BUTTON_UP,
    WPAD_PRO_BUTTON_DOWN,
    WPAD_PRO_TRIGGER_L,
    WPAD_PRO_TRIGGER_R,
    WPAD_PRO_TRIGGER_ZL,
    WPAD_PRO_TRIGGER_ZR,
    WPAD_PRO_BUTTON_PLUS,
    WPAD_PRO_BUTTON_MINUS,
    WPAD_PRO_BUTTON_STICK_L,
    WPAD_PRO_BUTTON_STICK_R,
    WPAD_PRO_BUTTON_HOME,
    0,
    0
};


int read_input();


#endif