// SPDX-License-Identifier: MIT

#ifndef NINTENDO_GLYPHS_HPP
#define NINTENDO_GLYPHS_HPP

#define NIN_GLYPH_BTN_A    "\uE000"
#define NIN_GLYPH_BTN_B    "\uE001"
#define NIN_GLYPH_BTN_X    "\uE002"
#define NIN_GLYPH_BTN_Y    "\uE003"
#define NIN_GLYPH_BTN_L    "\uE004"
#define NIN_GLYPH_BTN_R    "\uE005"
#define NIN_GLYPH_BTN_DPAD "\uE006"

// Used for touch screen calibration.
#define NIN_GLYPH_TARGET "\uE01D"

#define NIN_GLYPH_CAPTURE_STILL "\uE01E"
#define NIN_GLYPH_CAPTURE_VIDEO "\uE076"


#define NIN_GLYPH_SPINNER_0 "\uE020"
#define NIN_GLYPH_SPINNER_1 "\uE021"
#define NIN_GLYPH_SPINNER_2 "\uE022"
#define NIN_GLYPH_SPINNER_3 "\uE023"
#define NIN_GLYPH_SPINNER_4 "\uE024"
#define NIN_GLYPH_SPINNER_5 "\uE025"
#define NIN_GLYPH_SPINNER_6 "\uE026"
#define NIN_GLYPH_SPINNER_7 "\uE027"

#define NIN_GLYPH_WIIMOTE_BTN_POWER "\uE040"
#define NIN_GLYPH_WIIMOTE_BTN_DPAD  "\uE041"
#define NIN_GLYPH_WIIMOTE_BTN_A     "\uE042"
#define NIN_GLYPH_WIIMOTE_BTN_B     "\uE043"
#define NIN_GLYPH_WIIMOTE_BTN_HOME  "\uE044"
#define NIN_GLYPH_WIIMOTE_BTN_PLUS  "\uE045"
#define NIN_GLYPH_WIIMOTE_BTN_MINUS "\uE046"
#define NIN_GLYPH_WIIMOTE_BTN_1     "\uE047"
#define NIN_GLYPH_WIIMOTE_BTN_2     "\uE048"

#define NIN_GLYPH_NUNCHUK_STICK "\uE049"
#define NIN_GLYPH_NUNCHUK_BTN_C "\uE04A"
#define NIN_GLYPH_NUNCHUK_BTN_Z "\uE04B"

#define NIN_GLYPH_CLASSIC_BTN_DPAD  NIN_GLYPH_WIIMOTE_BTN_DPAD
#define NIN_GLYPH_CLASSIC_BTN_HOME  NIN_GLYPH_WIIMOTE_BTN_HOME
#define NIN_GLYPH_CLASSIC_BTN_PLUS  NIN_GLYPH_WIIMOTE_BTN_PLUS
#define NIN_GLYPH_CLASSIC_BTN_MINUS NIN_GLYPH_WIIMOTE_BTN_MINUS
#define NIN_GLYPH_CLASSIC_BTN_A     "\uE04C"
#define NIN_GLYPH_CLASSIC_BTN_B     "\uE04D"
#define NIN_GLYPH_CLASSIC_BTN_X     "\uE04E"
#define NIN_GLYPH_CLASSIC_BTN_Y     "\uE04F"
#define NIN_GLYPH_CLASSIC_L_STICK   "\uE050"
#define NIN_GLYPH_CLASSIC_R_STICK   "\uE051"
#define NIN_GLYPH_CLASSIC_BTN_L     "\uE052"
#define NIN_GLYPH_CLASSIC_BTN_R     "\uE053"
#define NIN_GLYPH_CLASSIC_BTN_ZL    "\uE054"
#define NIN_GLYPH_CLASSIC_BTN_ZR    "\uE055"

#define NIN_GLYPH_KBD_RETURN "\uE056"
#define NIN_GLYPH_KBD_SPACE  "\uE057"

#define NIN_GLYPH_HAND_POINT   "\uE058"
#define NIN_GLYPH_HAND_POINT_1 "\uE059"
#define NIN_GLYPH_HAND_POINT_2 "\uE05A"
#define NIN_GLYPH_HAND_POINT_3 "\uE05B"
#define NIN_GLYPH_HAND_POINT_4 "\uE05C"

#define NIN_GLYPH_HAND_FIST   "\uE05D"
#define NIN_GLYPH_HAND_FIST_1 "\uE05E"
#define NIN_GLYPH_HAND_FIST_2 "\uE05F"
#define NIN_GLYPH_HAND_FIST_3 "\uE060"
#define NIN_GLYPH_HAND_FIST_4 "\uE061"

#define NIN_GLYPH_HAND_OPEN   "\uE062"
#define NIN_GLYPH_HAND_OPEN_1 "\uE063"
#define NIN_GLYPH_HAND_OPEN_2 "\uE064"
#define NIN_GLYPH_HAND_OPEN_3 "\uE065"
#define NIN_GLYPH_HAND_OPEN_4 "\uE066"

// Wii logo
#define NIN_GLYPH_WII "\uE067"

// Question mark block icon.
#define NIN_GLYPH_HELP "\uE06B"

// Close icon.
#define NIN_GLYPH_CLOSE     "\uE070"
#define NIN_GLYPH_CLOSE_ALT "\uE071"

// Navigation images.
#define NIN_GLYPH_BACK "\uE072"
#define NIN_GLYPH_HOME "\uE073"

// Controller images.
#define NIN_GLYPH_GAMEPAD "\uE087"
#define NIN_GLYPH_WIIMOTE "\uE088"

#define NIN_GLYPH_3DS_BTN_DPAD  NIN_GLYPH_WIIMOTE_BTN_DPAD
#define NIN_GLYPH_3DS_BTN_A     NIN_GLYPH_BTN_A
#define NIN_GLYPH_3DS_BTN_B     NIN_GLYPH_BTN_B
#define NIN_GLYPH_3DS_BTN_X     NIN_GLYPH_BTN_X
#define NIN_GLYPH_3DS_BTN_Y     NIN_GLYPH_BTN_Y
#define NIN_GLYPH_3DS_BTN_HOME  NIN_GLYPH_HOME
#define NIN_GLYPH_3DS_CIRCLEPAD "\uE077"
#define NIN_GLYPH_3DS_BTN_POWER "\uE078"
#define NIN_GLYPH_3DS_STEPS     "\uE074"
#define NIN_GLYPH_3DS_PLAYCOIN  "\uE075"

#define NIN_GLYPH_BTN_DPAD_UP         "\uE079"
#define NIN_GLYPH_BTN_DPAD_DOWN       "\uE07A"
#define NIN_GLYPH_BTN_DPAD_LEFT       "\uE07B"
#define NIN_GLYPH_BTN_DPAD_RIGHT      "\uE07C"
#define NIN_GLYPH_BTN_DPAD_UP_DOWN    "\uE07D"
#define NIN_GLYPH_BTN_DPAD_DOWN_UP    NIN_GLYPH_BTN_DPAD_UP_DOWN
#define NIN_GLYPH_BTN_DPAD_LEFT_RIGHT "\uE07E"
#define NIN_GLYPH_BTN_DPAD_RIGHT_LEFT NIN_GLYPH_BTN_DPAD_LEFT_RIGHT

#define NIN_GLYPH_GAMEPAD_BTN_DPAD      NIN_GLYPH_WIIMOTE_BTN_DPAD
#define NIN_GLYPH_GAMEPAD_STICK         "\uE080"
#define NIN_GLYPH_GAMEPAD_L_STICK       "\uE081"
#define NIN_GLYPH_GAMEPAD_R_STICK       "\uE082"
#define NIN_GLYPH_GAMEPAD_BTN_L         "\uE083"
#define NIN_GLYPH_GAMEPAD_BTN_R         "\uE084"
#define NIN_GLYPH_GAMEPAD_BTN_ZL        "\uE085"
#define NIN_GLYPH_GAMEPAD_BTN_ZR        "\uE086"
#define NIN_GLYPH_GAMEPAD_BTN_HOME      NIN_GLYPH_WIIMOTE_BTN_HOME
#define NIN_GLYPH_GAMEPAD_BTN_PLUS      NIN_GLYPH_WIIMOTE_BTN_PLUS
#define NIN_GLYPH_GAMEPAD_BTN_MINUS     NIN_GLYPH_WIIMOTE_BTN_MINUS
#define NIN_GLYPH_GAMEPAD_BTN_TV        "\uE089"
#define NIN_GLYPH_GAMEPAD_L_STICK_PRESS "\uE08A"
#define NIN_GLYPH_GAMEPAD_R_STICK_PRESS "\uE08B"

#define NIN_GLYPH_ARROW_LEFT_RIGHT "\uE08C"
#define NIN_GLYPH_ARROW_RIGHT_LEFT NIN_GLYPH_ARROW_LEFT_RIGHT
#define NIN_GLYPH_ARROW_UP_DOWN    "\uE08D"
#define NIN_GLYPH_ARROW_DOWN_UP    NIN_GLYPH_ARROW_UP_DOWN

#define NIN_GLYPH_ARROW_CW  "\uE08E"
#define NIN_GLYPH_ARROW_CCW "\uE08F"

#define NIN_GLYPH_ARROW_RIGHT "\uE090"
#define NIN_GLYPH_ARROW_LEFT  "\uE091"
#define NIN_GLYPH_ARROW_UP    "\uE092"
#define NIN_GLYPH_ARROW_DOWN  "\uE093"

#define NIN_GLYPH_ARROW_UP_RIGHT   "\uE094"
#define NIN_GLYPH_ARROW_RIGHT_UP   NIN_GLYPH_ARROW_RIGHT_UP
#define NIN_GLYPH_ARROW_DOWN_RIGHT "\uE095"
#define NIN_GLYPH_ARROW_RIGHT_DOWN NIN_GLYPH_ARROW_DOWN_RIGHT
#define NIN_GLYPH_ARROW_DOWN_LEFT  "\uE096"
#define NIN_GLYPH_ARROW_LEFT_DOWN  NIN_GLYPH_ARROW_DOWN_LEFT
#define NIN_GLYPH_ARROW_UP_LEFT    "\uE097"
#define NIN_GLYPH_ARROW_LEFT_UP    NIN_GLYPH_ARROW_UP_LEFT

#define NIN_GLYPH_X "\uE098"

#define NIN_GLYPH_NFC "\uE099"

#endif